# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjJNaNSAw2E-pnyOXMkvTxSHtq7zAFFJ
"""

def descifrar_cesar(texto_cifrado, desplazamiento, alfabeto):
    texto_descifrado = ""
    for letra in texto_cifrado:
        if letra in alfabeto:
            indice_letra_cifrada = alfabeto.index(letra)
            indice_letra_original = (indice_letra_cifrada - desplazamiento) % len(alfabeto)
            letra_original = alfabeto[indice_letra_original]
            texto_descifrado += letra_original
        else:
            texto_descifrado += letra
    return texto_descifrado

alfabeto = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'
desplazamiento = 3
texto_cifrado = "ÑDSHUIHFFLPVHÑRJUDPRFXDPGRPRKDBPDGDOVTXHDQDGLUVLPRFXDPGRPRKDBPDGDOVTXHTXLWDU"


texto_descifrado = descifrar_cesar(texto_cifrado, desplazamiento, alfabeto)

print("Texto descifrado:", texto_descifrado)